#开启环境
spring:
  profiles:
    active: dev


#开启springDebug模式，打印已经自动配置的组件
#debug: true


--- #开发环境
spring:
  profiles: dev
  messages:
    #国际化配置基础名\
    basename: Internationalization.login
  #禁止模板引擎缓存（按住Ctrl+F9重新加入资源）
  thymeleaf:
    cache: false
server:
  port: 8888
  servlet:
    context-path: /xdd

#日志
logging:
  path: logs
  pattern:
    file: 【XDD288】 %d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n
  level:
    localhost: trace


--- #上线环境
spring:
  profiles: run
server:
  port: 80



