server:
  port: 9999
spring:
  profiles:
    active: test
#开启springDebug模式，打印已经自动配置的组件
debug: true

---
spring:
  profiles: test
server:
  port: 9876
  servlet:
    context-path: /xdd


---

spring:
  profiles: dev
server:
  port: 8899





#person:
#  name: 肖大大
#  age: 20
#  address: 湖南省衡南县
#  pets:
#    name: 吉姆猫
#    age: 5
#  hobby:
#    - 唱
#    - 跳
#    - rap
#  teachers:
#    math: 罗1素
#    Java_SE: 向生
#    Java_EE: 屈346


